### ISSUE TITLE
Mention that new sd card should be used for step 7

### ISSUE THREAD

**Issue by XavierElon** [treehouses/treehouses.github.io#160]
I have been made aware that we should be using a different SD card for step 7 than the one we used for step 1. 

>  Its preferred that you have 3 SD cards. The reason is, we'll be testing work with one, breaking something, then loading another SD and breaking it again to verify and document what causes a failure, and then using the 3rd for new testing as the 1st is rewritten. You can get by with 2, but there will be some down time that way.

I believe text like this should be added to Step 7 as that is what was told to me in the gitter chat.

**Comment by vmnet8** [comment]
I think it is a good suggestion, help person to clarify the confusion.

**Comment by CalebProvost** [comment]
Hm... It would be good as an elaboration; reasoning for the 3 SD cards yet explaining that one/two would work temporarily. 

I'm hesitant due to the fact that the [Pre-Requisites](https://treehouses.io/#!./pages/vi/firststeps.md#Pre-Requisites) already make note that 3 is needed.
I would focus the wording to state that using 1 or 2 while waiting for the rest to be mailed is doable, but upon being accepted to the VI its best to have the 3 ready.

I'd feel more comfortable getting @dogi's response to this before proceeding.
