### ISSUE TITLE
How to Remote  your RPI and Home network from anywhere !

### ISSUE THREAD

**Issue by jamjakpa** [treehouses/treehouses.github.io#308]
### Problem
I was sitting in my living room working on the internship Steps with a Starbucks Tea in my hand, and I was thinking about how great would that be to work from my Mothers place or my Grandmothers place or even anywhere on the Internship Steps. 

### Steps to reproduce the problem
N/A

### Install How to 

<p><a href="https://support-splashtoppersonal.splashtop.com/hc/en-us/articles/230009187-Basic-Remote-Manual">How To</a>.</p>

### Proposed solution
The Solution is <strong>Splashtop</strong>
<p><a href="https://www.splashtop.com/">Splashtop</a>.</p>

**Comment by john-dunbar** [comment]
I like the idea of having remote access. Here are some other [options I found](https://www.raspberrypi.org/documentation/remote-access/access-over-Internet/README.md).  

Also, I was thinking about how the steps said they use TOR for remote access because it is secure. And I started wondering if there is a SSH service over TOR. Well, it turns out there is [such a thing](https://www.khalidalnajjar.com/access-your-raspberry-pi-globally-using-tor/).

**Comment by jamjakpa** [comment]
> I like the idea of having remote access. Here are some other [options I found](https://www.raspberrypi.org/documentation/remote-access/access-over-Internet/README.md).
> 
> Also, I was thinking about how the steps said they use TOR for remote access because it is secure. And I started wondering if there is a SSH service over TOR. Well, it turns out there is [such a thing](https://www.khalidalnajjar.com/access-your-raspberry-pi-globally-using-tor/).

i think you can add port 22 ssh  TOR :

<code>treehouses tor add 22</code>

**Comment by dogi** [comment]
@dun08015 and @jamjakpa treehouses images is already configured for ssh over tor ...
