### ISSUE TITLE
Update to FAQ 

### ISSUE THREAD

**Issue by jayala-29** [treehouses/treehouses.github.io#465]
### Problem
Add steps to fix if user runs into issues setting up root SSH 

 ### Steps to reproduce the problem
Go to <https://treehouses.io/#!./pages/vi/faq.md>

 ### Screenshots
N/A

 ### Proposed solution
Add solution with regards to problem stated above

**Comment by LordJashin32** [comment]
I think this section is warranted but I think we would want it answered differently. You need to add your SSH keys in order to login as root with the treehouses image. ```treehouses sshkey github adduser username```. Then your login with root will work. Permitting root login is another method but less secure perhaps. You need to add a SSH key to your github account. Then http://github.com/username.keys should have your public RSA key. Your private key should be on your computers that want to access the pi. Then the public key and private key work together and grant you login access. Otherwise you gotta login with pi as the user with ssh.

**Comment by jayala-29** [comment]
Ah I see, feel free to close my PR on treehouses master or let me know how I should proceed.

**Comment by LordJashin32** [comment]
> Ah I see, feel free to close my PR on treehouses master or let me know how I should proceed.

I think you proceeded appropriately. You can always update your PR. It doesn't have to be perfect on the first try. Cheers.

**Comment by dogi** [comment]
@jayala-29 thanks for understanding
