### ISSUE TITLE
Clarifying microSD card requirement in firststeps.md

### ISSUE THREAD

**Issue by law-lin** [treehouses/treehouses.github.io#508]
### Problem
Currently, only 2 microSD cards are required to complete the First Steps (steps 1 + 2 and step 7). Yet, the hardware requirement states 3 microSD cards.

 ### Steps to reproduce the problem
Visit firststeps.md to see the requirements.

 ### Screenshots
![image](https://user-images.githubusercontent.com/35390215/79320630-1ba42780-7ed8-11ea-8712-13f5ff006e0b.png)

 ### Proposed solution
Be more specific in the requirements. Change "3 microSD cards" to "2-3 microSD cards" with the bullet point "2 microSD cards are required for completing these first steps, but 1 more microSD card is recommended for use in the internship itself".

**Comment by LordJashin32** [comment]
Up to @dogi on this one. I think the preferred is 2 or more SD cards with the minimum perhaps being 1 technically. I only ever use one. I have a backup though. So perhaps we should clarify for backup purpose as well.

**Comment by dogi** [comment]
@LordJashin32 I know that you are doing that, and since you are so exceptionally awesome I ignore that you are not following standard protocol ;)

Anyhow @law-lin for the internship I want you to have 3 and I insist on that ;)
I do also not wanna go into the slippery slope of saying we need 2-3
or we recommend 3
right now because of COVID look-downs I willing to make some temporary exceptions
but I think there is no need to write that ...

I hope @law-lin you understand ;) 


... maybe on step7  we add an other task where we use the 3rd sdcard in combination with `treehouses remote` and make people find issues on our android app

**Comment by LordJashin32** [comment]
so to sum this up. Change 1-2 to 3. Cheers.

**Comment by law-lin** [comment]
Closing this as the description on the page already has 3 as the requirements.
