### ISSUE TITLE
github-issues.md needs "we" "our" instead of "you" "your"

### ISSUE THREAD

**Issue by LordJashin32** [treehouses/treehouses.github.io#559]
Mainly because it sounds better. And "you" "your" is hardly ever used because its rude/improper. It can be taken as singling out. I don't take it that way. But most english people would say to use "we" and "our" instead. And since this is a team. Even more so then.

**Comment by warthog16** [comment]
Hmm, since the whole first steps seems to be directives or instructions, using second person might make more sense. Either way, second person (eg., you, your) is used throughout the whole First Steps and not just github-issues.md which might make it difficult to rephrase everything from the beginning.
