### ISSUE TITLE
write faq quick start for people which are  Steps Ordering

### ISSUE THREAD

**Issue by thatgirlprogrammer** [treehouses/treehouses.github.io#751]
### Instructions not Grouped Based on whether One Needs a Pi or Not
Some instructions can be done before one has gotten a raspberry pi while others cannot. Steps 1, 2, 4, and 7 require a raspberry pi. The others do not.

 ### Steps to reproduce the problem
NA

 ### Screenshots
<img width="350" alt="Capture2" src="https://user-images.githubusercontent.com/21347558/97781846-616ac980-1b64-11eb-8633-181254f5cab2.PNG">
<img width="372" alt="capture3" src="https://user-images.githubusercontent.com/21347558/97781847-616ac980-1b64-11eb-8b1b-c125d4c3aa56.PNG">
<img width="338" alt="Capture1" src="https://user-images.githubusercontent.com/21347558/97781848-62036000-1b64-11eb-8105-429333dba8a8.PNG">

 ### Proposed solution
Reorder the instructs to have the ones that require that raspberry pi last.

**Comment by dogi** [comment]
thanks @thatgirlprogrammer for this suggestion,
but reordering steps is out of question
we designed the flow of the steps exact this way
so that when all requirements are available you get the maximum speed
between interacting with the team and the rpi and learning new things

what about writing a special section in the FAQ where we speak about which steps can be done without rpi

**Comment by farzana184** [comment]
I had the same thought that reordering would help to perform steps with raspberry pi consecutively but if it helps in learning then writing a section in the FAQ or at the beginning of the steps would be helpful.
