### ISSUE TITLE
404 error in treehouses.io in MoodleMoot Philippines 2018 blog post

### ISSUE THREAD

**Issue by manav113** [treehouses/treehouses.github.io#831]
### Problem

A 404 Not Found error code gets thrown in the [blog post](https://treehouses.io/#!./pages/blog/20180505-moodlemootph18.md) , indicating the PDF file doesn't exist.
 ### Steps to reproduce the problem
Go to https://treehouses.io/#!./pages/blog/20180505-moodlemootph18.md

 ### Screenshots
![Screenshot from 2021-03-24 18-26-18](https://user-images.githubusercontent.com/57234825/112314067-9839ab80-8cce-11eb-9bf4-b4b601e9fe74.png)

 ### Proposed solution
N/A.

**Comment by RCW2000** [comment]
If the link is correct and the document no longer exists maybe we could replace the pdf with something else that showcases the LMS and/or treehouses/remote, like an image or logo or diagram. Since this is an old blog post it may make more sense to just delete the link and/or not change anything at all.

**Comment by dogi** [comment]
@RCW2000 just remove the included inline pdf
